# Generated by Django 5.2.3 on 2025-06-25 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(max_length=50, unique=True, verbose_name="標籤"),
                ),
            ],
            options={
                "verbose_name": "問題標籤",
                "verbose_name_plural": "問題標籤",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="英文名稱"),
                ),
                (
                    "c_name",
                    models.CharField(max_length=100, unique=True, verbose_name="中文名稱"),
                ),
            ],
            options={
                "verbose_name": "主題",
                "verbose_name_plural": "主題",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "level",
                    models.CharField(
                        choices=[("easy", "簡單"), ("medium", "中等"), ("hard", "困難")],
                        max_length=10,
                        verbose_name="難度",
                    ),
                ),
                ("input_format", models.TextField(verbose_name="輸入格式")),
                ("output_format", models.TextField(verbose_name="輸出格式")),
                ("input_example", models.TextField(verbose_name="輸入範例")),
                ("output_example", models.TextField(verbose_name="輸出範例")),
                ("answer", models.TextField(verbose_name="答案")),
                (
                    "hint",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="提示"
                    ),
                ),
                (
                    "reference",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="參考資料"
                    ),
                ),
                (
                    "answer_display",
                    models.BooleanField(default=False, verbose_name="顯示答案"),
                ),
                (
                    "as_homework",
                    models.BooleanField(default=False, verbose_name="作為作業"),
                ),
                ("is_approved", models.BooleanField(default=False, verbose_name="已批准")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="瀏覽次數"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="擁有者",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="questions.questiontag", verbose_name="標籤"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(to="questions.topic", verbose_name="主題"),
                ),
            ],
            options={
                "verbose_name": "問題",
                "verbose_name_plural": "問題",
            },
        ),
        migrations.CreateModel(
            name="QuestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "創建"),
                            ("updated", "更新"),
                            ("deleted", "刪除"),
                        ],
                        max_length=50,
                        verbose_name="動作",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="時間戳"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                        verbose_name="問題",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "問題日誌",
                "verbose_name_plural": "問題日誌",
            },
        ),
        migrations.CreateModel(
            name="QuestionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "level",
                    models.CharField(
                        choices=[("easy", "簡單"), ("medium", "中等"), ("hard", "困難")],
                        max_length=10,
                        verbose_name="難度",
                    ),
                ),
                ("input_format", models.TextField(verbose_name="輸入格式")),
                ("output_format", models.TextField(verbose_name="輸出格式")),
                ("input_example", models.TextField(verbose_name="輸入範例")),
                ("output_example", models.TextField(verbose_name="輸出範例")),
                ("answer", models.TextField(verbose_name="答案")),
                (
                    "hint",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="提示"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="參考資料"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版本")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="questions.question",
                        verbose_name="問題",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="questions.questiontag", verbose_name="標籤"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(to="questions.topic", verbose_name="主題"),
                ),
            ],
            options={
                "verbose_name": "問題歷史",
                "verbose_name_plural": "問題歷史",
            },
        ),
    ]
