# Generated by Django 5.2.3 on 2025-06-22 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "c_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Chinese Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "c_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Chinese Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Tag",
                "verbose_name_plural": "News Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news_images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Source Name",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Is Published"),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_units",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_units",
                        to="news.newscategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="news_units", to="news.newstag"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Unit",
                "verbose_name_plural": "News Units",
                "ordering": ["-published_date"],
            },
        ),
    ]
