# Generated by Django 5.2 on 2025-08-09 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="分類名稱")),
                ("description", models.TextField(blank=True, verbose_name="分類描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "回報分類",
                "verbose_name_plural": "回報分類",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="回報內容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理"),
                            ("in_progress", "處理中"),
                            ("approved", "已處理"),
                            ("rejected", "棄單"),
                            ("closed", "已關閉"),
                        ],
                        default="pending",
                        max_length=255,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解決時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.category",
                        verbose_name="回報分類",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回報用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "回報",
                "verbose_name_plural": "回報",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "建立"), ("update", "更新"), ("delete", "刪除")],
                        max_length=255,
                        verbose_name="操作類型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作使用者",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reports.report",
                        verbose_name="回報",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日誌",
                "verbose_name_plural": "操作日誌",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="reports/attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="附件圖片",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始檔名"),
                ),
                ("file_size", models.PositiveIntegerField(verbose_name="檔案大小(bytes)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.report",
                        verbose_name="回報",
                    ),
                ),
            ],
            options={
                "verbose_name": "回報附件圖片",
                "verbose_name_plural": "回報附件圖片",
            },
        ),
    ]
