# Generated by Django 5.2.3 on 2025-07-31 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='類型名稱')),
                ('description', models.TextField(blank=True, verbose_name='類型描述')),
            ],
            options={
                'verbose_name': '教材類型',
                'verbose_name_plural': '教材類型',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='單元標題')),
                ('description', models.TextField(blank=True, verbose_name='單元描述')),
                ('order', models.PositiveIntegerField(verbose_name='排序順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '單元',
                'verbose_name_plural': '單元',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='教材標題')),
                ('content', models.TextField(blank=True, verbose_name='教材描述')),
                ('order', models.PositiveIntegerField(verbose_name='排序順序')),
                ('pdf_file', models.FileField(upload_to='materials/pdfs/', verbose_name='PDF檔案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialcategory', verbose_name='教材類型')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.unit', verbose_name='所屬單元')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
                'ordering': ['order'],
            },
        ),
    ]
