# Generated by Django 5.2 on 2025-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureToggle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="功能名稱"),
                ),
                ("description", models.TextField(blank=True, verbose_name="功能描述")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "功能開關",
                "verbose_name_plural": "功能開關",
                "ordering": ["name"],
            },
        ),
    ]
