# Generated by Django 5.2 on 2025-07-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("difficulty_score", models.TextField(verbose_name="AI 難度分數")),
                ("feedback", models.TextField(verbose_name="AI 回饋")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DifficultyEvaluationQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_questions",
                        to="ai.difficultyevaluation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_difficulties",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "難度評估題目關聯",
                "verbose_name_plural": "難度評估題目關聯",
                "unique_together": {("evaluation", "question")},
            },
        ),
    ]
